### ISSUE TITLE
fix node_modules

### ISSUE THREAD

**Issue by peterbrendel** [RicardoStoklosa/CleberBot#5]
I believe you don't need all the modules in the package for your solution. 
I suggest a refactor on that in order to squish the file size and get better readability for users.

Peter.

**Comment by RicardoStoklosa** [comment]
Actually, it is needed to remove the node_modules folder and add a dependency npm file.

# RICARDO.

**Comment by peterbrendel** [comment]
Oh okay, sorry for my bad english.

### - [x] **` Peter.`**

**Comment by RicardoStoklosa** [comment]
~não há de quê~| 
------------ |
